## 翰林院GitLab-CI使用须知
##
## 需要在GitLab对应项目中设置BUILD_ENV BUILD_PATH JUNIT_REPORTS参数,
## GitLab 设置位置project->settings->ci/cd->environment variables
## BUILD_ENV 编译工具：maven gradle node
## BUILD_PATH 编译目录：
##   maven: target/*.jar | target/*.war
##   gradle: build/libs/*.jar | build/libs/*.war
##   node: dist
## JUNIT_REPORTS junit测试报告路径
##   maven: target/*-reports/TEST-*.xml
##   gradle: build/test-results/test/TEST-*.xml
##
## 需要在GitLab对应项目所在组或项目中设置DOCKER_PRI_REGISTRY REGISTRY_USER REGISTRY_PWD KUBE_NAMESPACE参数,
## DOCKER_PRI_REGISTRY docker私有仓库域名
## REGISTRY_USER docker私有仓库登录用户名
## REGISTRY_PWD docker私有仓库登录密码
## KUBE_NAMESPACE k8s部署命名空间 统一为gitlab-managed-apps

include:
  - project: 'hanlin/open-source/hanlin-gitlab-ci'
    file: '.gitlab-ci-template.yml'
    ref: 'without-git-except-test'
