
# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maven.sino-hanlin.tech:30005/sandbox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
podArgs:
  - "-Djava.security.egd=file:/dev/./urandom"
  - "-Duser.timezone=GMT+08"
  - "-Djava.awt.headless=true"
  - "-Dfile.encoding=UTF-8"
  - "-XX:+HeapDumpOnOutOfMemoryError"
  - "-XX:HeapDumpPath=/application/logs/hs_err_pid%p.hprof"
  - "-XX:+PrintGCDetails"
  - "-XX:+PrintGCDateStamps"
  - "-XX:+PrintTenuringDistribution"
  - "-XX:+PrintHeapAtGC"
  - "-XX:+PrintGCApplicationStoppedTime"
  - "-XX:+PrintReferenceGC"
  - "-XX:+UseGCLogFileRotation"
  - "-XX:NumberOfGCLogFiles=10"
  - "-XX:GCLogFileSize=100M"
  - "-Xloggc:/application/logs/gc-%t.log"
  - "-server"

podRuntimeArgs: []

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

deploymentAnnotations: {}
  # app.gitlab.com/env:
  # app.gitlab.com/app:

# 如果存在prometheus依赖，则开启对应监听端点
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"
  prometheus.io/path: "/actuator/prometheus"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 400m
  #  memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: hanlin.arch/enviroment
          operator: Exists


