
# Default values for project.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: maven.sino-hanlin.tech:30005/sandbox
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

## application
application: {}
  # track: stable | canary
  # tier: stage | production | canary

## 翰林院GitLab环境参数
gitlab: {}
  #app: application-name
  #env: environment-name

## 应用VM启动参数
vm:
  options:
  - "-Djava.security.egd=file:/dev/./urandom"
  - "-Duser.timezone=GMT+08"
  - "-Djava.awt.headless=true"
  - "-Dfile.encoding=UTF-8"
  - "-XX:+HeapDumpOnOutOfMemoryError"
  - "-XX:HeapDumpPath=/application/logs/hs_err_pid%p.hprof"
  - "-XX:+PrintGCDetails"
  - "-XX:+PrintGCDateStamps"
  - "-XX:+PrintTenuringDistribution"
  - "-XX:+PrintHeapAtGC"
  - "-XX:+PrintGCApplicationStoppedTime"
  - "-XX:+PrintReferenceGC"
  - "-XX:+UseGCLogFileRotation"
  - "-XX:NumberOfGCLogFiles=10"
  - "-XX:GCLogFileSize=100M"
  - "-Xloggc:/application/logs/gc-%t.log"
  - "-server"

## program args
program:
  args: {}

## serivceAccount
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

## prometheus annotations
# 如果存在prometheus依赖，则开启对应监听端点
prometheus:
  metrics: "true"

## livenessProbe & readinessProbe
livenessProbe:
  probeType: "httpGet"
  path: /actuator/health/liveness
  initialDelaySeconds: 10
  timeoutSeconds: 30
readinessProbe:
  probeType: "httpGet"
  path: /actuator/health/readiness
  initialDelaySeconds: 10
  timeoutSeconds: 30

## podSecurityContext
podSecurityContext: {}
  # fsGroup: 2000

## securityContext of the container
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

## service
service:
  enabled: true
  name: web
  type: ClusterIP
  # 默认应用使用8080端口
  internalPort: 8080
  externalPort: 8080

## 持久化配置 persistence
persistence:
  enabled: false
  volumes: {}

## intgress
ingress:
  enabled: false
  className: "nginx"
  certmanager:
    enabled: false
  #  type: ["cluster-issuer" | "issuer"]
  #  issuer: "letsencrypt-staging"
  hosts: {}
  #   - host: chart-example.local
  #     paths:
  #       - path: /
  #         pathType: ImplementationSpecific
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
  canary: {}
    # weight: 100

## resources
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 400m
  #  memory: 512Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

## autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

## nodeSelector
nodeSelector: {}

## tolerations
tolerations: []

## affinity
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: hanlin.arch/enviroment
          operator: Exists


